# Generated by Django 2.1.5 on 2019-01-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('preciocosto', models.DecimalField(decimal_places=8, max_digits=10)),
                ('precioventa', models.DecimalField(decimal_places=8, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('stockminimo', models.IntegerField()),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compra.Proveedor')),
            ],
        ),
    ]
