# Generated by Django 2.1.5 on 2019-01-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('apeparterno', models.CharField(max_length=50)),
                ('apemarterno', models.CharField(max_length=50)),
                ('numerodocumento', models.CharField(max_length=20)),
                ('web', models.CharField(max_length=100)),
                ('razonsocial', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('celular', models.CharField(max_length=12)),
                ('direccion', models.TextField()),
            ],
        ),
    ]
