# Generated by Django 2.1.5 on 2019-01-16 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numerodocumento', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apeparterno', models.CharField(max_length=50)),
                ('apemarterno', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('fechanacimiento', models.DateField()),
                ('fecharegistro', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
                ('celular', models.CharField(max_length=12)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pendiente', models.DecimalField(decimal_places=8, max_digits=10)),
                ('fecha', models.DateField()),
                ('fechavencimiento', models.DateField()),
                ('tipocambio', models.DecimalField(decimal_places=8, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.Cliente')),
                ('producto', models.ManyToManyField(blank=True, to='almacen.Producto')),
            ],
        ),
    ]
